name: CI to Snowflake

on: [push, workflow_dispatch]

jobs:
  run-snowflake:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Get GitHub OIDC Token
        id: oidc
        run: |
          TOKEN=$(curl -s \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=snowflake" | jq -r '.value')
    
          echo "SNOWFLAKE_TOKEN=$TOKEN" >> $GITHUB_OUTPUT
          echo "$TOKEN"

      - name: print token
        run: |
            echo "$SNOWFLAKE_TOKEN"
