name: CI to Snowflake

on: [push, workflow_dispatch]

jobs:
  run-snowflake:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Get GitHub OIDC Token
        id: oidc
        run: |
          TOKEN=$(curl -s \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=snowflake" | jq -r '.value')
    
          echo "SNOWFLAKE_TOKEN1=$TOKEN" >> $GITHUB_ENV
          echo "$TOKEN"

      - name: print token
        run: |
            echo "$SNOWFLAKE_TOKEN1"

      - name: Decode token safely
        run: |
          PAYLOAD=$(echo "$SNOWFLAKE_TOKEN1" | cut -d '.' -f2)
          echo "$PAYLOAD" | base64 -d 2>/dev/null | jq '{aud, iss, sub, preferred_username, scp, appid, role}'

      - name: Connect to Snowflake
        run: |
          pip install snowflake-connector-python
          python snowflake_test1.py
