name: CI to Snowflake

on: [push, workflow_dispatch]

jobs:
  run-snowflake:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Get GitHub OIDC Token
        id: oidc
        run: |
          echo "::set-output name=token::$(curl -s \
            -H \"Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN\" \
            \"https://token.actions.githubusercontent.com?audience=snowflake\")"

      - name: print token
        run: |
            echo "${{ steps.oidc.outputs.token }}"
