name: CI to Snowflake

on: [push, workflow_dispatch]

jobs:
  run-snowflake:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Get GitHub OIDC Token
        id: oidc
        run: |
          TOKEN=$(curl -s \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=snowflake" | jq -r '.value')
    
          echo "SNOWFLAKE_TOKEN2=$TOKEN" >> $GITHUB_ENV
          echo "$TOKEN"

      - name: print token
        run: |
            echo "$SNOWFLAKE_TOKEN2"

      # - name: Decode token safely
      #   run: |
      #     PAYLOAD=$(echo "$SNOWFLAKE_TOKEN2" | cut -d '.' -f2)
      #     echo "$PAYLOAD" | base64 -d 2>/dev/null | jq '{aud, iss, sub, preferred_username, scp, appid, role}'

      - name: Exchange token
        run: |
          SF_TOKEN=$(curl -v -X POST \
          https://ranaqbw-np18722.snowflakecomputing.com/oauth/token-request \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
          -d "subject_token_type=urn:ietf:params:oauth:token-type:jwt" \
          -d "subject_token=$SNOWFLAKE_TOKEN2" \
          -d "scope=session:role-any")

          echo "SNOWFLAKE_TOKEN1=$SF_TOKEN" >> $GITHUB_ENV
          echo "$SF_TOKEN"

      - name: Decode token safely
        run: |
          PAYLOAD=$(echo "$SNOWFLAKE_TOKEN1" | cut -d '.' -f2)
          echo "$PAYLOAD" | base64 -d 2>/dev/null | jq '{aud, iss, sub, preferred_username, scp, appid, role}'

      - name: Connect to Snowflake
        run: |
          pip install snowflake-connector-python
          python snowflake_test1.py
